apiVersion: v1
kind: Service
metadata:
  name: base-service
spec:
  type: LoadBalancer
  selector:
    app: base-service
  ports:
    - protocol: TCP
      port: 5003 # External port
      targetPort: 5003 # Container port
